package org.bouncycastle.asn1.p042x9;

import com.google.android.exoplayer2.metadata.icy.IcyHeaders;
import com.google.android.exoplayer2.source.rtsp.SessionDescription;
import org.bouncycastle.asn1.ASN1ObjectIdentifier;
/* renamed from: org.bouncycastle.asn1.x9.X9ObjectIdentifiers */
/* loaded from: classes4.dex */
public interface X9ObjectIdentifiers {
    public static final ASN1ObjectIdentifier ansi_X9_42;
    public static final ASN1ObjectIdentifier ansi_X9_62;
    public static final ASN1ObjectIdentifier cTwoCurve;
    public static final ASN1ObjectIdentifier characteristic_two_field;
    public static final ASN1ObjectIdentifier ecdsa_with_SHA2;
    public static final ASN1ObjectIdentifier ellipticCurve;
    public static final ASN1ObjectIdentifier id_ecSigType;
    public static final ASN1ObjectIdentifier id_fieldType;
    public static final ASN1ObjectIdentifier id_publicKeyType;
    public static final ASN1ObjectIdentifier ppBasis;
    public static final ASN1ObjectIdentifier prime192v1;
    public static final ASN1ObjectIdentifier prime256v1;
    public static final ASN1ObjectIdentifier primeCurve;
    public static final ASN1ObjectIdentifier prime_field;
    public static final ASN1ObjectIdentifier tpBasis;
    public static final ASN1ObjectIdentifier x9_42_schemes;
    public static final ASN1ObjectIdentifier x9_44;
    public static final ASN1ObjectIdentifier x9_44_components;
    public static final ASN1ObjectIdentifier x9_63_scheme;

    static {
        ASN1ObjectIdentifier aSN1ObjectIdentifier = new ASN1ObjectIdentifier("1.2.840.10045");
        ansi_X9_62 = aSN1ObjectIdentifier;
        ASN1ObjectIdentifier branch = aSN1ObjectIdentifier.branch(IcyHeaders.REQUEST_HEADER_ENABLE_METADATA_VALUE);
        id_fieldType = branch;
        prime_field = branch.branch(IcyHeaders.REQUEST_HEADER_ENABLE_METADATA_VALUE);
        ASN1ObjectIdentifier branch2 = branch.branch("2");
        characteristic_two_field = branch2;
        branch2.branch("3.1");
        tpBasis = branch2.branch("3.2");
        ppBasis = branch2.branch("3.3");
        ASN1ObjectIdentifier branch3 = aSN1ObjectIdentifier.branch("4");
        id_ecSigType = branch3;
        branch3.branch(IcyHeaders.REQUEST_HEADER_ENABLE_METADATA_VALUE);
        ASN1ObjectIdentifier branch4 = aSN1ObjectIdentifier.branch("2");
        id_publicKeyType = branch4;
        branch4.branch(IcyHeaders.REQUEST_HEADER_ENABLE_METADATA_VALUE);
        ASN1ObjectIdentifier branch5 = branch3.branch("3");
        ecdsa_with_SHA2 = branch5;
        branch5.branch(IcyHeaders.REQUEST_HEADER_ENABLE_METADATA_VALUE);
        branch5.branch("2");
        branch5.branch("3");
        branch5.branch("4");
        ASN1ObjectIdentifier branch6 = aSN1ObjectIdentifier.branch("3");
        ellipticCurve = branch6;
        ASN1ObjectIdentifier branch7 = branch6.branch(SessionDescription.SUPPORTED_SDP_VERSION);
        cTwoCurve = branch7;
        branch7.branch(IcyHeaders.REQUEST_HEADER_ENABLE_METADATA_VALUE);
        branch7.branch("2");
        branch7.branch("3");
        branch7.branch("4");
        branch7.branch("5");
        branch7.branch("6");
        branch7.branch("7");
        branch7.branch("8");
        branch7.branch("9");
        branch7.branch("10");
        branch7.branch("11");
        branch7.branch("12");
        branch7.branch("13");
        branch7.branch("14");
        branch7.branch("15");
        branch7.branch("16");
        branch7.branch("17");
        branch7.branch("18");
        branch7.branch("19");
        branch7.branch("20");
        ASN1ObjectIdentifier branch8 = branch6.branch(IcyHeaders.REQUEST_HEADER_ENABLE_METADATA_VALUE);
        primeCurve = branch8;
        prime192v1 = branch8.branch(IcyHeaders.REQUEST_HEADER_ENABLE_METADATA_VALUE);
        branch8.branch("2");
        branch8.branch("3");
        branch8.branch("4");
        branch8.branch("5");
        branch8.branch("6");
        prime256v1 = branch8.branch("7");
        new ASN1ObjectIdentifier("1.2.840.10040.4.1");
        new ASN1ObjectIdentifier("1.2.840.10040.4.3");
        ASN1ObjectIdentifier aSN1ObjectIdentifier2 = new ASN1ObjectIdentifier("1.3.133.16.840.63.0");
        x9_63_scheme = aSN1ObjectIdentifier2;
        aSN1ObjectIdentifier2.branch("2");
        aSN1ObjectIdentifier2.branch("3");
        aSN1ObjectIdentifier2.branch("16");
        ASN1ObjectIdentifier aSN1ObjectIdentifier3 = new ASN1ObjectIdentifier("1.2.840.10046");
        ansi_X9_42 = aSN1ObjectIdentifier3;
        aSN1ObjectIdentifier3.branch("2.1");
        ASN1ObjectIdentifier branch9 = aSN1ObjectIdentifier3.branch("3");
        x9_42_schemes = branch9;
        branch9.branch(IcyHeaders.REQUEST_HEADER_ENABLE_METADATA_VALUE);
        branch9.branch("2");
        branch9.branch("3");
        branch9.branch("4");
        branch9.branch("5");
        branch9.branch("6");
        branch9.branch("7");
        branch9.branch("8");
        ASN1ObjectIdentifier aSN1ObjectIdentifier4 = new ASN1ObjectIdentifier("1.3.133.16.840.9.44");
        x9_44 = aSN1ObjectIdentifier4;
        ASN1ObjectIdentifier branch10 = aSN1ObjectIdentifier4.branch(IcyHeaders.REQUEST_HEADER_ENABLE_METADATA_VALUE);
        x9_44_components = branch10;
        branch10.branch(IcyHeaders.REQUEST_HEADER_ENABLE_METADATA_VALUE);
        branch10.branch("2");
    }
}
