package com.smedialink.common;
/* loaded from: classes3.dex */
public class IdFabric$Menu {
    public static final int CHAT_ADD_TO_BOOKMARKS;
    public static final int CHAT_ADD_TO_FOLDER;
    public static final int CHAT_ALBUMS;
    public static final int CHAT_BOOKMARKS;
    public static final int CHAT_CLEAR_CACHE;
    public static final int CHAT_CLOUD_LOCK;
    public static final int CHAT_CLOUD_OPEN_BY_DEFAULT;
    public static final int CHAT_DONATE;
    public static final int CHAT_JUMP_TO_START;
    public static final int CHAT_REMOVE_FROM_BOOKMARKS;
    public static final int CHAT_SELECT_TOPIC;
    public static final int CHAT_TOGGLE_ALBUM;
    public static final int CHAT_TRANSLATE_SETTINGS;
    public static final int CONTACTS_PRIVACY_SETTINGS;
    public static final int COPY;
    public static final int DELETE;
    public static final int DIALOGS_ALBUMS_CLOUD;
    public static final int DIALOGS_ALBUMS_OPEN_BY_DEFAULT;
    public static final int DIALOGS_ARCHIVE_LOCK;
    public static final int DIALOGS_CHAT_SETTINGS;
    public static final int DIALOGS_CLEAR_CACHE;
    public static final int DIALOGS_MANAGEMENT_DELETE_ALL;
    public static final int DIALOGS_MOVE_TO_FOLDER;
    public static final int DIALOGS_SCAN_LOGIN_QR_CODE;
    public static final int DIALOGS_SCROLL_TO_END;
    public static final int DIALOGS_SCROLL_TO_START;
    public static final int DIALOGS_SELECT_TOPIC;
    public static final int DIALOGS_SORT_ALBUMS;
    public static final int DIALOGS_TOOLS_SETTINGS;
    public static final int EDIT_AND_SEND;
    public static final int GROUP_MESSAGES;
    public static final int INFO;
    public static final int LANGUAGE;
    public static final int LOGOUT;
    public static final int MESSAGE_COPY_IMAGE;
    public static final int MESSAGE_COPY_PART;
    public static final int MESSAGE_DELETE_FROM_CACHE;
    public static final int MESSAGE_EDIT_TEMPLATE;
    public static final int MESSAGE_FORWARD_CLOUD;
    public static final int MESSAGE_FORWARD_VIBER;
    public static final int MESSAGE_FORWARD_WHATSAPP;
    public static final int MESSAGE_FORWARD_WHATSAPP_BUSINESS;
    public static final int MESSAGE_RESTORE_BACKUP;
    public static final int MESSAGE_SAVE_AS;
    public static final int NETWORK_SWITCH;
    public static final int NFT_COPY_ID;
    public static final int NFT_OPEN_CONTRACT;
    public static final int NFT_OPEN_SOURCE;
    public static final int NOTIFICATIONS;
    public static final int OPEN_IN_TWITTER;
    public static final int OPTIONS;
    public static final int PDF;
    public static final int PHOTO_COPY;
    public static final int PHOTO_OBJECTS;
    public static final int PHOTO_TEXT;
    public static final int PINNED_PLAYER_TOGGLE_COMPACT;
    public static final int PINNED_PLAYER_TOGGLE_THEME;
    public static final int PROFILE_SERVICE_MESSAGES;

    /* renamed from: QR */
    public static final int f257QR;
    public static final int QUOTE = -1073741824;
    public static final int REACTIONS;
    public static final int RECEIVE;
    public static final int REJECT;
    public static final int REPORT;
    public static final int RESET;
    public static final int SCAN_ADDRESS;
    public static final int SEARCH_QR;
    public static final int SEARCH_TEL;
    public static final int SEARCH_TWITTER;
    public static final int SEND_AS_GIF;
    public static final int SEND_SILENT;
    public static final int SETTINGS;
    public static final int SET_AS_AVATAR;
    public static final int SHARE;
    public static final int SORT;
    public static final int STAKING_CONDITIONS;
    public static final int STAKING_CONTRACT;
    public static final int STAKING_HELP;
    public static final int STAKING_WEBSITE;
    public static final int SWITCH_ACCOUNT;
    public static final int SWITCH_ARCHIVE;
    public static final int TOGGLE_AUTO_PREVIEW;
    public static final int TOGGLE_MUSIC_PLAYLIST;
    public static final int TOKEN_SITE;
    public static final int TOKEN_SMART_CONTRACT_ADDRESS;
    public static final int TOKEN_STATISTICS;
    public static final int TON_ADDRESS_V3R2;
    public static final int TRANSLATE;
    public static final int UNGROUP_MESSAGES;
    public static final int UNPIN_PLAYER;
    public static final int WALLET_CONNECT;

    /* renamed from: id */
    private static int f258id = -1073741824;

    static {
        int i = (-1073741824) + 1;
        f258id = i;
        int i2 = i + 1;
        f258id = i2;
        LOGOUT = i;
        int i3 = i2 + 1;
        f258id = i3;
        NOTIFICATIONS = i2;
        int i4 = i3 + 1;
        f258id = i4;
        NETWORK_SWITCH = i3;
        int i5 = i4 + 1;
        f258id = i5;
        SHARE = i4;
        int i6 = i5 + 1;
        f258id = i6;
        COPY = i5;
        int i7 = i6 + 1;
        f258id = i7;
        OPTIONS = i6;
        int i8 = i7 + 1;
        f258id = i8;
        PDF = i7;
        int i9 = i8 + 1;
        f258id = i9;
        REPORT = i8;
        int i10 = i9 + 1;
        f258id = i10;
        TOKEN_SMART_CONTRACT_ADDRESS = i9;
        int i11 = i10 + 1;
        f258id = i11;
        TOKEN_STATISTICS = i10;
        int i12 = i11 + 1;
        f258id = i12;
        TOKEN_SITE = i11;
        int i13 = i12 + 1;
        f258id = i13;
        SCAN_ADDRESS = i12;
        int i14 = i13 + 1;
        f258id = i14;
        RESET = i13;
        int i15 = i14 + 1;
        f258id = i15;
        REJECT = i14;
        int i16 = i15 + 1;
        f258id = i16;
        RECEIVE = i15;
        int i17 = i16 + 1;
        f258id = i17;
        WALLET_CONNECT = i16;
        int i18 = i17 + 1;
        f258id = i18;
        SORT = i17;
        int i19 = i18 + 1;
        f258id = i19;
        DELETE = i18;
        int i20 = i19 + 1;
        f258id = i20;
        TOGGLE_AUTO_PREVIEW = i19;
        int i21 = i20 + 1;
        f258id = i21;
        TOGGLE_MUSIC_PLAYLIST = i20;
        int i22 = i21 + 1;
        f258id = i22;
        UNPIN_PLAYER = i21;
        int i23 = i22 + 1;
        f258id = i23;
        PINNED_PLAYER_TOGGLE_COMPACT = i22;
        int i24 = i23 + 1;
        f258id = i24;
        PINNED_PLAYER_TOGGLE_THEME = i23;
        int i25 = i24 + 1;
        f258id = i25;
        SEARCH_QR = i24;
        int i26 = i25 + 1;
        f258id = i26;
        SEARCH_TEL = i25;
        int i27 = i26 + 1;
        f258id = i27;
        SEARCH_TWITTER = i26;
        int i28 = i27 + 1;
        f258id = i28;
        f257QR = i27;
        int i29 = i28 + 1;
        f258id = i29;
        LANGUAGE = i28;
        int i30 = i29 + 1;
        f258id = i30;
        SEND_SILENT = i29;
        int i31 = i30 + 1;
        f258id = i31;
        SEND_AS_GIF = i30;
        int i32 = i31 + 1;
        f258id = i32;
        EDIT_AND_SEND = i31;
        int i33 = i32 + 1;
        f258id = i33;
        NFT_COPY_ID = i32;
        int i34 = i33 + 1;
        f258id = i34;
        NFT_OPEN_CONTRACT = i33;
        int i35 = i34 + 1;
        f258id = i35;
        NFT_OPEN_SOURCE = i34;
        int i36 = i35 + 1;
        f258id = i36;
        SET_AS_AVATAR = i35;
        int i37 = i36 + 1;
        f258id = i37;
        SETTINGS = i36;
        int i38 = i37 + 1;
        f258id = i38;
        REACTIONS = i37;
        int i39 = i38 + 1;
        f258id = i39;
        TRANSLATE = i38;
        int i40 = i39 + 1;
        f258id = i40;
        SWITCH_ACCOUNT = i39;
        int i41 = i40 + 1;
        f258id = i41;
        SWITCH_ARCHIVE = i40;
        int i42 = i41 + 1;
        f258id = i42;
        CONTACTS_PRIVACY_SETTINGS = i41;
        int i43 = i42 + 1;
        f258id = i43;
        PROFILE_SERVICE_MESSAGES = i42;
        int i44 = i43 + 1;
        f258id = i44;
        MESSAGE_COPY_PART = i43;
        int i45 = i44 + 1;
        f258id = i45;
        MESSAGE_COPY_IMAGE = i44;
        int i46 = i45 + 1;
        f258id = i46;
        MESSAGE_RESTORE_BACKUP = i45;
        int i47 = i46 + 1;
        f258id = i47;
        MESSAGE_SAVE_AS = i46;
        int i48 = i47 + 1;
        f258id = i48;
        MESSAGE_EDIT_TEMPLATE = i47;
        int i49 = i48 + 1;
        f258id = i49;
        MESSAGE_FORWARD_CLOUD = i48;
        int i50 = i49 + 1;
        f258id = i50;
        MESSAGE_FORWARD_WHATSAPP = i49;
        int i51 = i50 + 1;
        f258id = i51;
        MESSAGE_FORWARD_WHATSAPP_BUSINESS = i50;
        int i52 = i51 + 1;
        f258id = i52;
        MESSAGE_FORWARD_VIBER = i51;
        int i53 = i52 + 1;
        f258id = i53;
        MESSAGE_DELETE_FROM_CACHE = i52;
        int i54 = i53 + 1;
        f258id = i54;
        CHAT_TRANSLATE_SETTINGS = i53;
        int i55 = i54 + 1;
        f258id = i55;
        CHAT_JUMP_TO_START = i54;
        int i56 = i55 + 1;
        f258id = i56;
        CHAT_CLEAR_CACHE = i55;
        int i57 = i56 + 1;
        f258id = i57;
        CHAT_ALBUMS = i56;
        int i58 = i57 + 1;
        f258id = i58;
        CHAT_ADD_TO_FOLDER = i57;
        int i59 = i58 + 1;
        f258id = i59;
        CHAT_TOGGLE_ALBUM = i58;
        int i60 = i59 + 1;
        f258id = i60;
        CHAT_SELECT_TOPIC = i59;
        int i61 = i60 + 1;
        f258id = i61;
        CHAT_CLOUD_OPEN_BY_DEFAULT = i60;
        int i62 = i61 + 1;
        f258id = i62;
        CHAT_CLOUD_LOCK = i61;
        int i63 = i62 + 1;
        f258id = i63;
        CHAT_BOOKMARKS = i62;
        int i64 = i63 + 1;
        f258id = i64;
        CHAT_ADD_TO_BOOKMARKS = i63;
        int i65 = i64 + 1;
        f258id = i65;
        CHAT_REMOVE_FROM_BOOKMARKS = i64;
        int i66 = i65 + 1;
        f258id = i66;
        CHAT_DONATE = i65;
        int i67 = i66 + 1;
        f258id = i67;
        DIALOGS_SORT_ALBUMS = i66;
        int i68 = i67 + 1;
        f258id = i68;
        DIALOGS_ALBUMS_CLOUD = i67;
        int i69 = i68 + 1;
        f258id = i69;
        DIALOGS_ALBUMS_OPEN_BY_DEFAULT = i68;
        int i70 = i69 + 1;
        f258id = i70;
        DIALOGS_SCAN_LOGIN_QR_CODE = i69;
        int i71 = i70 + 1;
        f258id = i71;
        DIALOGS_TOOLS_SETTINGS = i70;
        int i72 = i71 + 1;
        f258id = i72;
        DIALOGS_CHAT_SETTINGS = i71;
        int i73 = i72 + 1;
        f258id = i73;
        DIALOGS_CLEAR_CACHE = i72;
        int i74 = i73 + 1;
        f258id = i74;
        DIALOGS_SCROLL_TO_END = i73;
        int i75 = i74 + 1;
        f258id = i75;
        DIALOGS_SCROLL_TO_START = i74;
        int i76 = i75 + 1;
        f258id = i76;
        DIALOGS_MOVE_TO_FOLDER = i75;
        int i77 = i76 + 1;
        f258id = i77;
        DIALOGS_SELECT_TOPIC = i76;
        int i78 = i77 + 1;
        f258id = i78;
        DIALOGS_ARCHIVE_LOCK = i77;
        int i79 = i78 + 1;
        f258id = i79;
        DIALOGS_MANAGEMENT_DELETE_ALL = i78;
        int i80 = i79 + 1;
        f258id = i80;
        PHOTO_COPY = i79;
        int i81 = i80 + 1;
        f258id = i81;
        PHOTO_TEXT = i80;
        int i82 = i81 + 1;
        f258id = i82;
        PHOTO_OBJECTS = i81;
        int i83 = i82 + 1;
        f258id = i83;
        GROUP_MESSAGES = i82;
        int i84 = i83 + 1;
        f258id = i84;
        UNGROUP_MESSAGES = i83;
        int i85 = i84 + 1;
        f258id = i85;
        STAKING_CONTRACT = i84;
        int i86 = i85 + 1;
        f258id = i86;
        STAKING_WEBSITE = i85;
        int i87 = i86 + 1;
        f258id = i87;
        STAKING_CONDITIONS = i86;
        int i88 = i87 + 1;
        f258id = i88;
        STAKING_HELP = i87;
        int i89 = i88 + 1;
        f258id = i89;
        TON_ADDRESS_V3R2 = i88;
        int i90 = i89 + 1;
        f258id = i90;
        INFO = i89;
        f258id = i90 + 1;
        OPEN_IN_TWITTER = i90;
    }
}
