package com.smedialink.common;
/* loaded from: classes3.dex */
public class IdFabric$ViewTypes {
    public static final int ALBUM;
    public static final int BANNERS;
    public static final int BINANCE_ACCOUNT;
    public static final int BUTTON;
    public static final int CARD_BUTTON;
    public static final int CATALOG_CAMPAIGN;
    public static final int CATALOG_CATEGORY_WITH_CAMPAIGNS;
    public static final int CATALOG_CREATE;
    public static final int CENTRALIZED_EXCHANGES;
    public static final int CHAT_ATTACH_ALERT_BUTTON;
    public static final int CHAT_ATTACH_FOOTER;
    public static final int CHAT_ATTACH_HEADER;
    public static final int CHOOSE_FEE;
    public static final int CHOOSE_RECIPIENT_OPTIONS;
    public static final int CONTACTS_FILTER;
    public static final int CONTACTS_INPUT_ADDRESS;
    public static final int CREATE_ACCOUNT;
    public static final int CREATE_ALBUM;
    public static final int CRYPTO_ACCOUNT;
    public static final int DRAWER_ALBUMS;
    public static final int DRAWER_CATALOG;
    public static final int DRAWER_GROUP_CREATE;
    public static final int DRAWER_MANAGEMENT;
    public static final int DRAWER_MUSIC;
    public static final int DRAWER_WALLET;
    public static final int EMPTY;
    public static final int FABS;
    public static final int FILTERS_LIST;
    public static final int FOOTER;
    public static final int GLOBAL_STATE;
    public static final int HEADER = -1073741824;
    public static final int HEADER_WITH_IMAGE_VIEW_BUTTON;
    public static final int HEADER_WITH_NETWORK_SWITCHER;
    public static final int HEADER_WITH_RIGHT_BUTTON;
    public static final int IMAGE_RADIO;
    public static final int LANGUAGE;
    public static final int LOADING;
    public static final int MOVING_CHECK;
    public static final int MOVING_REACTION;
    public static final int MUSIC_NO_PERMISSION;
    public static final int NFT_AVATAR;
    public static final int NFT_COLLECTION;
    public static final int NOTIFICATION_CHECK;
    public static final int PRODUCT_FOR_BUY;
    public static final int PROFILE_SEARCH;
    public static final int SEARCH_TEL;
    public static final int SELECTABLE_HEADER;
    public static final int SELECT_TOKENS;
    public static final int SERVICES_BASIC;
    public static final int SHADOW_SECTION;
    public static final int SHARED_AUDIO;
    public static final int SHARED_AUDIO_CELL_MUSIC;
    public static final int SLIDE;
    public static final int SLIDE_CHOOSE;
    public static final int SORTING_FILTER;
    public static final int STAKING_ACTIONS;
    public static final int STAKING_DASHBOARD;
    public static final int STAKING_INFO;
    public static final int STAKING_OPERATION;
    public static final int STAKING_PROGNOSIS;
    public static final int STAKING_PROGRAMME;
    public static final int STAKING_SAFE_WITHDRAWAL;
    public static final int STAKING_WITHDRAWAL_FEE;
    public static final int SUB_ITEM_BOTTOM;
    public static final int SUB_ITEM_GAP;
    public static final int SUB_ITEM_MIDDLE;
    public static final int SUB_ITEM_TOP;
    public static final int SWAP_PROTOCOL;
    public static final int TEMPLATE;
    public static final int TEXT;
    public static final int TEXT_CHECK;
    public static final int TEXT_CHECK_BOX;
    public static final int TEXT_DETAIL_WITH_RANK;
    public static final int TEXT_INFO_PRIVACY;
    public static final int TEXT_NETWORK_SWITCHER;
    public static final int TEXT_SETTINGS;
    public static final int TOKEN_BALANCE;
    public static final int TON_ADDRESS_VERSION;
    public static final int TOPIC;
    public static final int TOPICS_BAR;
    public static final int TOTAL_BALANCE;
    public static final int TRANSACTION;
    public static final int TWEET;
    public static final int TWEETS_DATE;
    public static final int TWITTER;
    public static final int TWITTER_INVITE;
    public static final int TWITTER_USER;
    public static final int URL_BUTTON;
    public static final int VIEW_TYPE_EXPANDABLE_SWITCH;
    public static final int VIEW_TYPE_INNER_CHECK;
    public static final int WALLET_CONNECT_SESSION;

    /* renamed from: id */
    private static int f261id = -1073741824;

    static {
        int i = (-1073741824) + 1;
        f261id = i;
        int i2 = i + 1;
        f261id = i2;
        GLOBAL_STATE = i;
        int i3 = i2 + 1;
        f261id = i3;
        SELECTABLE_HEADER = i2;
        int i4 = i3 + 1;
        f261id = i4;
        TOKEN_BALANCE = i3;
        int i5 = i4 + 1;
        f261id = i5;
        BINANCE_ACCOUNT = i4;
        int i6 = i5 + 1;
        f261id = i6;
        CRYPTO_ACCOUNT = i5;
        int i7 = i6 + 1;
        f261id = i7;
        CREATE_ACCOUNT = i6;
        int i8 = i7 + 1;
        f261id = i8;
        SERVICES_BASIC = i7;
        int i9 = i8 + 1;
        f261id = i9;
        TOTAL_BALANCE = i8;
        int i10 = i9 + 1;
        f261id = i10;
        SELECT_TOKENS = i9;
        int i11 = i10 + 1;
        f261id = i11;
        HEADER_WITH_NETWORK_SWITCHER = i10;
        int i12 = i11 + 1;
        f261id = i12;
        HEADER_WITH_IMAGE_VIEW_BUTTON = i11;
        int i13 = i12 + 1;
        f261id = i13;
        HEADER_WITH_RIGHT_BUTTON = i12;
        int i14 = i13 + 1;
        f261id = i14;
        BANNERS = i13;
        int i15 = i14 + 1;
        f261id = i15;
        SLIDE = i14;
        int i16 = i15 + 1;
        f261id = i16;
        CENTRALIZED_EXCHANGES = i15;
        int i17 = i16 + 1;
        f261id = i17;
        SWAP_PROTOCOL = i16;
        int i18 = i17 + 1;
        f261id = i18;
        TRANSACTION = i17;
        int i19 = i18 + 1;
        f261id = i19;
        STAKING_OPERATION = i18;
        int i20 = i19 + 1;
        f261id = i20;
        FOOTER = i19;
        int i21 = i20 + 1;
        f261id = i21;
        PRODUCT_FOR_BUY = i20;
        int i22 = i21 + 1;
        f261id = i22;
        CONTACTS_FILTER = i21;
        int i23 = i22 + 1;
        f261id = i23;
        CONTACTS_INPUT_ADDRESS = i22;
        int i24 = i23 + 1;
        f261id = i24;
        CHOOSE_FEE = i23;
        int i25 = i24 + 1;
        f261id = i25;
        BUTTON = i24;
        int i26 = i25 + 1;
        f261id = i26;
        MOVING_CHECK = i25;
        int i27 = i26 + 1;
        f261id = i27;
        WALLET_CONNECT_SESSION = i26;
        int i28 = i27 + 1;
        f261id = i28;
        TEMPLATE = i27;
        int i29 = i28 + 1;
        f261id = i29;
        CHAT_ATTACH_HEADER = i28;
        int i30 = i29 + 1;
        f261id = i30;
        CHAT_ATTACH_FOOTER = i29;
        int i31 = i30 + 1;
        f261id = i31;
        SHADOW_SECTION = i30;
        int i32 = i31 + 1;
        f261id = i32;
        TEXT_NETWORK_SWITCHER = i31;
        int i33 = i32 + 1;
        f261id = i33;
        IMAGE_RADIO = i32;
        int i34 = i33 + 1;
        f261id = i34;
        TEXT_CHECK = i33;
        int i35 = i34 + 1;
        f261id = i35;
        TEXT_SETTINGS = i34;
        int i36 = i35 + 1;
        f261id = i36;
        TEXT = i35;
        int i37 = i36 + 1;
        f261id = i37;
        NOTIFICATION_CHECK = i36;
        int i38 = i37 + 1;
        f261id = i38;
        TEXT_INFO_PRIVACY = i37;
        int i39 = i38 + 1;
        f261id = i39;
        SLIDE_CHOOSE = i38;
        int i40 = i39 + 1;
        f261id = i40;
        TEXT_CHECK_BOX = i39;
        int i41 = i40 + 1;
        f261id = i41;
        PROFILE_SEARCH = i40;
        int i42 = i41 + 1;
        f261id = i42;
        EMPTY = i41;
        int i43 = i42 + 1;
        f261id = i43;
        MUSIC_NO_PERMISSION = i42;
        int i44 = i43 + 1;
        f261id = i44;
        LOADING = i43;
        int i45 = i44 + 1;
        f261id = i45;
        SHARED_AUDIO = i44;
        int i46 = i45 + 1;
        f261id = i46;
        SEARCH_TEL = i45;
        int i47 = i46 + 1;
        f261id = i47;
        NFT_COLLECTION = i46;
        int i48 = i47 + 1;
        f261id = i48;
        NFT_AVATAR = i47;
        int i49 = i48 + 1;
        f261id = i49;
        CARD_BUTTON = i48;
        int i50 = i49 + 1;
        f261id = i50;
        CATALOG_CATEGORY_WITH_CAMPAIGNS = i49;
        int i51 = i50 + 1;
        f261id = i51;
        CATALOG_CAMPAIGN = i50;
        int i52 = i51 + 1;
        f261id = i52;
        CATALOG_CREATE = i51;
        int i53 = i52 + 1;
        f261id = i53;
        SHARED_AUDIO_CELL_MUSIC = i52;
        int i54 = i53 + 1;
        f261id = i54;
        LANGUAGE = i53;
        int i55 = i54 + 1;
        f261id = i55;
        int i56 = i55 + 1;
        f261id = i56;
        ALBUM = i55;
        int i57 = i56 + 1;
        f261id = i57;
        CREATE_ALBUM = i56;
        int i58 = i57 + 1;
        f261id = i58;
        FABS = i57;
        int i59 = i58 + 1;
        f261id = i59;
        TOPIC = i58;
        int i60 = i59 + 1;
        f261id = i60;
        TEXT_DETAIL_WITH_RANK = i59;
        int i61 = i60 + 1;
        f261id = i61;
        MOVING_REACTION = i60;
        int i62 = i61 + 1;
        f261id = i62;
        URL_BUTTON = i61;
        int i63 = i62 + 1;
        f261id = i63;
        TOPICS_BAR = i62;
        int i64 = i63 + 1;
        f261id = i64;
        CHAT_ATTACH_ALERT_BUTTON = i63;
        int i65 = i64 + 1;
        f261id = i65;
        SORTING_FILTER = i64;
        int i66 = i65 + 1;
        f261id = i66;
        DRAWER_GROUP_CREATE = i65;
        int i67 = i66 + 1;
        f261id = i67;
        DRAWER_ALBUMS = i66;
        int i68 = i67 + 1;
        f261id = i68;
        DRAWER_WALLET = i67;
        int i69 = i68 + 1;
        f261id = i69;
        DRAWER_CATALOG = i68;
        int i70 = i69 + 1;
        f261id = i70;
        DRAWER_MANAGEMENT = i69;
        int i71 = i70 + 1;
        f261id = i71;
        DRAWER_MUSIC = i70;
        int i72 = i71 + 1;
        f261id = i72;
        SUB_ITEM_TOP = i71;
        int i73 = i72 + 1;
        f261id = i73;
        SUB_ITEM_MIDDLE = i72;
        int i74 = i73 + 1;
        f261id = i74;
        SUB_ITEM_BOTTOM = i73;
        int i75 = i74 + 1;
        f261id = i75;
        SUB_ITEM_GAP = i74;
        int i76 = i75 + 1;
        f261id = i76;
        STAKING_INFO = i75;
        int i77 = i76 + 1;
        f261id = i77;
        STAKING_ACTIONS = i76;
        int i78 = i77 + 1;
        f261id = i78;
        STAKING_SAFE_WITHDRAWAL = i77;
        int i79 = i78 + 1;
        f261id = i79;
        STAKING_WITHDRAWAL_FEE = i78;
        int i80 = i79 + 1;
        f261id = i80;
        STAKING_DASHBOARD = i79;
        int i81 = i80 + 1;
        f261id = i81;
        STAKING_PROGRAMME = i80;
        int i82 = i81 + 1;
        f261id = i82;
        STAKING_PROGNOSIS = i81;
        int i83 = i82 + 1;
        f261id = i83;
        TON_ADDRESS_VERSION = i82;
        int i84 = i83 + 1;
        f261id = i84;
        FILTERS_LIST = i83;
        int i85 = i84 + 1;
        f261id = i85;
        VIEW_TYPE_EXPANDABLE_SWITCH = i84;
        int i86 = i85 + 1;
        f261id = i86;
        VIEW_TYPE_INNER_CHECK = i85;
        int i87 = i86 + 1;
        f261id = i87;
        TWITTER = i86;
        int i88 = i87 + 1;
        f261id = i88;
        TWITTER_USER = i87;
        int i89 = i88 + 1;
        f261id = i89;
        TWITTER_INVITE = i88;
        int i90 = i89 + 1;
        f261id = i90;
        TWEET = i89;
        int i91 = i90 + 1;
        f261id = i91;
        TWEETS_DATE = i90;
        f261id = i91 + 1;
        CHOOSE_RECIPIENT_OPTIONS = i91;
    }
}
