name: Test to get iMe version
on: workflow_dispatch
env:
  IME_VERSION: not-set
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: get version
        run: |
            export IME_TEST=0.0.0
            printenv IME_TEST
            grep 'versionName' apktool.yml | cut -d' ' -f 4
            grep 'versionName' apktool.yml | cut -d' ' -f 4 >> IME_TEST
            printenv IME_TEST