package com.iMe.common;
/* loaded from: classes4.dex */
public class IdFabric$Menu {
    public static final int ADD_TOKEN;
    public static final int ADMIN_CATEGORIES_FILTER;
    public static final int ALL_CHATS_CATEGORIES_FILTER;
    public static final int BOTS_CATEGORIES_FILTER;
    public static final int CHANNELS_CATEGORIES_FILTER;
    public static final int CHAT_ADD_TO_FOLDER;
    public static final int CHAT_ALBUMS;
    public static final int CHAT_CLEAR_CACHE;
    public static final int CHAT_CLOUD_LOCK;
    public static final int CHAT_CLOUD_OPEN_BY_DEFAULT;
    public static final int CHAT_DONATE;
    public static final int CHAT_JUMP_TO_START;
    public static final int CHAT_SELECT_TOPIC;
    public static final int CHAT_TOGGLE_ALBUM;
    public static final int CHAT_TRANSLATE_SETTINGS;
    public static final int CONTACTS_PRIVACY_SETTINGS;
    public static final int COPY;
    public static final int DELETE;
    public static final int DIALOGS_ALBUMS_CLOUD;
    public static final int DIALOGS_ALBUMS_OPEN_BY_DEFAULT;
    public static final int DIALOGS_ARCHIVE_LOCK;
    public static final int DIALOGS_CHAT_SETTINGS;
    public static final int DIALOGS_CLEAR_CACHE;
    public static final int DIALOGS_MOVE_TO_FOLDER;
    public static final int DIALOGS_SCAN_LOGIN_QR_CODE;
    public static final int DIALOGS_SCROLL_TO_END;
    public static final int DIALOGS_SCROLL_TO_START;
    public static final int DIALOGS_SELECT_TOPIC;
    public static final int DIALOGS_SORT_ALBUMS;
    public static final int DIALOGS_TOOLS_SETTINGS;
    public static final int EDIT_AND_SEND;
    public static final int GROUPS_CHATS_CATEGORIES_FILTER;
    public static final int GROUP_MESSAGES;
    public static final int INFO;
    public static final int LANGUAGE;
    public static final int LOGOUT;
    public static final int MESSAGE_COPY_IMAGE;
    public static final int MESSAGE_COPY_PART;
    public static final int MESSAGE_DELETE_FROM_CACHE;
    public static final int MESSAGE_EDIT_TEMPLATE;
    public static final int MESSAGE_FORWARD_CLOUD;
    public static final int MESSAGE_FORWARD_VIBER;
    public static final int MESSAGE_FORWARD_WHATSAPP;
    public static final int MESSAGE_FORWARD_WHATSAPP_BUSINESS;
    public static final int MESSAGE_RESTORE_BACKUP;
    public static final int MESSAGE_SAVE_AS;
    public static final int MESSAGE_SAVE_CLOUD;
    public static final int NETWORK_SWITCH;
    public static final int NFT_COPY_ID;
    public static final int NFT_OPEN_CONTRACT;
    public static final int NFT_OPEN_SOURCE;
    public static final int NOTIFICATIONS;
    public static final int OPEN_IN_TWITTER;
    public static final int OPTIONS;
    public static final int OWNER_CATEGORIES_FILTER;
    public static final int PDF;
    public static final int PERSONAL_CHATS_CATEGORIES_FILTER;
    public static final int PHOTO_COPY;
    public static final int PHOTO_OBJECTS;
    public static final int PHOTO_TEXT;
    public static final int PINNED_PLAYER_TOGGLE_COMPACT;
    public static final int PINNED_PLAYER_TOGGLE_THEME;
    public static final int PRIVATE_GROUPS_CATEGORIES_FILTER;
    public static final int PROFILE_SERVICE_MESSAGES;
    public static final int PUBLIC_GROUPS__CATEGORIES_FILTER;

    /* renamed from: QR */
    public static final int f339QR;
    public static final int QUOTE = -1073741824;
    public static final int REACTIONS;
    public static final int RECEIVE;
    public static final int REPORT;
    public static final int RESET;
    public static final int RESET_TWITTER;
    public static final int SCAN_ADDRESS;
    public static final int SEARCH;
    public static final int SEARCH_QR;
    public static final int SEARCH_TEL;
    public static final int SEND_AS_GIF;
    public static final int SETTINGS;
    public static final int SET_AS_AVATAR;
    public static final int SHARE;
    public static final int SMART_CONTRACT;
    public static final int SORT;
    public static final int STAKING_CONDITIONS;
    public static final int STAKING_HELP;
    public static final int STAKING_WEBSITE;
    public static final int SWITCH_ACCOUNT;
    public static final int TOGGLE_ARCHIVE;
    public static final int TOGGLE_AUTO_PREVIEW;
    public static final int TOGGLE_HIDDEN_CHATS;
    public static final int TOGGLE_MUSIC_PLAYLIST;
    public static final int TOKEN_INFORMATION;
    public static final int TOKEN_SITE;
    public static final int TOKEN_STATISTICS;
    public static final int TON_ADDRESS_V3R2;
    public static final int TRANSLATE;
    public static final int UNGROUP_MESSAGES;
    public static final int UNPIN_PLAYER;
    public static final int WALLET_CONNECT;

    /* renamed from: id */
    private static int f340id = -1073741824;

    static {
        int i = (-1073741824) + 1;
        f340id = i;
        int i2 = i + 1;
        f340id = i2;
        LOGOUT = i;
        int i3 = i2 + 1;
        f340id = i3;
        NOTIFICATIONS = i2;
        int i4 = i3 + 1;
        f340id = i4;
        NETWORK_SWITCH = i3;
        int i5 = i4 + 1;
        f340id = i5;
        SHARE = i4;
        int i6 = i5 + 1;
        f340id = i6;
        COPY = i5;
        int i7 = i6 + 1;
        f340id = i7;
        OPTIONS = i6;
        int i8 = i7 + 1;
        f340id = i8;
        PDF = i7;
        int i9 = i8 + 1;
        f340id = i9;
        REPORT = i8;
        int i10 = i9 + 1;
        f340id = i10;
        TOKEN_INFORMATION = i9;
        int i11 = i10 + 1;
        f340id = i11;
        TOKEN_STATISTICS = i10;
        int i12 = i11 + 1;
        f340id = i12;
        TOKEN_SITE = i11;
        int i13 = i12 + 1;
        f340id = i13;
        SCAN_ADDRESS = i12;
        int i14 = i13 + 1;
        f340id = i14;
        RESET = i13;
        int i15 = i14 + 1;
        f340id = i15;
        int i16 = i15 + 1;
        f340id = i16;
        RECEIVE = i15;
        int i17 = i16 + 1;
        f340id = i17;
        WALLET_CONNECT = i16;
        int i18 = i17 + 1;
        f340id = i18;
        SORT = i17;
        int i19 = i18 + 1;
        f340id = i19;
        DELETE = i18;
        int i20 = i19 + 1;
        f340id = i20;
        TOGGLE_AUTO_PREVIEW = i19;
        int i21 = i20 + 1;
        f340id = i21;
        TOGGLE_MUSIC_PLAYLIST = i20;
        int i22 = i21 + 1;
        f340id = i22;
        UNPIN_PLAYER = i21;
        int i23 = i22 + 1;
        f340id = i23;
        PINNED_PLAYER_TOGGLE_COMPACT = i22;
        int i24 = i23 + 1;
        f340id = i24;
        PINNED_PLAYER_TOGGLE_THEME = i23;
        int i25 = i24 + 1;
        f340id = i25;
        SEARCH_QR = i24;
        int i26 = i25 + 1;
        f340id = i26;
        SEARCH_TEL = i25;
        int i27 = i26 + 1;
        f340id = i27;
        SEARCH = i26;
        int i28 = i27 + 1;
        f340id = i28;
        f339QR = i27;
        int i29 = i28 + 1;
        f340id = i29;
        LANGUAGE = i28;
        int i30 = i29 + 1;
        f340id = i30;
        SEND_AS_GIF = i29;
        int i31 = i30 + 1;
        f340id = i31;
        EDIT_AND_SEND = i30;
        int i32 = i31 + 1;
        f340id = i32;
        NFT_COPY_ID = i31;
        int i33 = i32 + 1;
        f340id = i33;
        NFT_OPEN_CONTRACT = i32;
        int i34 = i33 + 1;
        f340id = i34;
        NFT_OPEN_SOURCE = i33;
        int i35 = i34 + 1;
        f340id = i35;
        SET_AS_AVATAR = i34;
        int i36 = i35 + 1;
        f340id = i36;
        SETTINGS = i35;
        int i37 = i36 + 1;
        f340id = i37;
        REACTIONS = i36;
        int i38 = i37 + 1;
        f340id = i38;
        TRANSLATE = i37;
        int i39 = i38 + 1;
        f340id = i39;
        SWITCH_ACCOUNT = i38;
        int i40 = i39 + 1;
        f340id = i40;
        TOGGLE_ARCHIVE = i39;
        int i41 = i40 + 1;
        f340id = i41;
        CONTACTS_PRIVACY_SETTINGS = i40;
        int i42 = i41 + 1;
        f340id = i42;
        PROFILE_SERVICE_MESSAGES = i41;
        int i43 = i42 + 1;
        f340id = i43;
        MESSAGE_COPY_PART = i42;
        int i44 = i43 + 1;
        f340id = i44;
        MESSAGE_COPY_IMAGE = i43;
        int i45 = i44 + 1;
        f340id = i45;
        MESSAGE_RESTORE_BACKUP = i44;
        int i46 = i45 + 1;
        f340id = i46;
        MESSAGE_SAVE_AS = i45;
        int i47 = i46 + 1;
        f340id = i47;
        MESSAGE_EDIT_TEMPLATE = i46;
        int i48 = i47 + 1;
        f340id = i48;
        MESSAGE_FORWARD_CLOUD = i47;
        int i49 = i48 + 1;
        f340id = i49;
        MESSAGE_SAVE_CLOUD = i48;
        int i50 = i49 + 1;
        f340id = i50;
        MESSAGE_FORWARD_WHATSAPP = i49;
        int i51 = i50 + 1;
        f340id = i51;
        MESSAGE_FORWARD_WHATSAPP_BUSINESS = i50;
        int i52 = i51 + 1;
        f340id = i52;
        MESSAGE_FORWARD_VIBER = i51;
        int i53 = i52 + 1;
        f340id = i53;
        MESSAGE_DELETE_FROM_CACHE = i52;
        int i54 = i53 + 1;
        f340id = i54;
        CHAT_TRANSLATE_SETTINGS = i53;
        int i55 = i54 + 1;
        f340id = i55;
        CHAT_JUMP_TO_START = i54;
        int i56 = i55 + 1;
        f340id = i56;
        CHAT_CLEAR_CACHE = i55;
        int i57 = i56 + 1;
        f340id = i57;
        CHAT_ALBUMS = i56;
        int i58 = i57 + 1;
        f340id = i58;
        CHAT_ADD_TO_FOLDER = i57;
        int i59 = i58 + 1;
        f340id = i59;
        CHAT_TOGGLE_ALBUM = i58;
        int i60 = i59 + 1;
        f340id = i60;
        CHAT_SELECT_TOPIC = i59;
        int i61 = i60 + 1;
        f340id = i61;
        CHAT_CLOUD_OPEN_BY_DEFAULT = i60;
        int i62 = i61 + 1;
        f340id = i62;
        CHAT_CLOUD_LOCK = i61;
        int i63 = i62 + 1;
        f340id = i63;
        CHAT_DONATE = i62;
        int i64 = i63 + 1;
        f340id = i64;
        DIALOGS_SORT_ALBUMS = i63;
        int i65 = i64 + 1;
        f340id = i65;
        DIALOGS_ALBUMS_CLOUD = i64;
        int i66 = i65 + 1;
        f340id = i66;
        DIALOGS_ALBUMS_OPEN_BY_DEFAULT = i65;
        int i67 = i66 + 1;
        f340id = i67;
        DIALOGS_SCAN_LOGIN_QR_CODE = i66;
        int i68 = i67 + 1;
        f340id = i68;
        DIALOGS_TOOLS_SETTINGS = i67;
        int i69 = i68 + 1;
        f340id = i69;
        DIALOGS_CHAT_SETTINGS = i68;
        int i70 = i69 + 1;
        f340id = i70;
        DIALOGS_CLEAR_CACHE = i69;
        int i71 = i70 + 1;
        f340id = i71;
        DIALOGS_SCROLL_TO_END = i70;
        int i72 = i71 + 1;
        f340id = i72;
        DIALOGS_SCROLL_TO_START = i71;
        int i73 = i72 + 1;
        f340id = i73;
        DIALOGS_MOVE_TO_FOLDER = i72;
        int i74 = i73 + 1;
        f340id = i74;
        DIALOGS_SELECT_TOPIC = i73;
        int i75 = i74 + 1;
        f340id = i75;
        DIALOGS_ARCHIVE_LOCK = i74;
        int i76 = i75 + 1;
        f340id = i76;
        PHOTO_COPY = i75;
        int i77 = i76 + 1;
        f340id = i77;
        PHOTO_TEXT = i76;
        int i78 = i77 + 1;
        f340id = i78;
        PHOTO_OBJECTS = i77;
        int i79 = i78 + 1;
        f340id = i79;
        GROUP_MESSAGES = i78;
        int i80 = i79 + 1;
        f340id = i80;
        UNGROUP_MESSAGES = i79;
        int i81 = i80 + 1;
        f340id = i81;
        SMART_CONTRACT = i80;
        int i82 = i81 + 1;
        f340id = i82;
        STAKING_WEBSITE = i81;
        int i83 = i82 + 1;
        f340id = i83;
        STAKING_CONDITIONS = i82;
        int i84 = i83 + 1;
        f340id = i84;
        STAKING_HELP = i83;
        int i85 = i84 + 1;
        f340id = i85;
        TON_ADDRESS_V3R2 = i84;
        int i86 = i85 + 1;
        f340id = i86;
        INFO = i85;
        int i87 = i86 + 1;
        f340id = i87;
        OPEN_IN_TWITTER = i86;
        int i88 = i87 + 1;
        f340id = i88;
        RESET_TWITTER = i87;
        int i89 = i88 + 1;
        f340id = i89;
        TOGGLE_HIDDEN_CHATS = i88;
        int i90 = i89 + 1;
        f340id = i90;
        ADD_TOKEN = i89;
        int i91 = i90 + 1;
        f340id = i91;
        ALL_CHATS_CATEGORIES_FILTER = i90;
        int i92 = i91 + 1;
        f340id = i92;
        PERSONAL_CHATS_CATEGORIES_FILTER = i91;
        int i93 = i92 + 1;
        f340id = i93;
        GROUPS_CHATS_CATEGORIES_FILTER = i92;
        int i94 = i93 + 1;
        f340id = i94;
        PRIVATE_GROUPS_CATEGORIES_FILTER = i93;
        int i95 = i94 + 1;
        f340id = i95;
        PUBLIC_GROUPS__CATEGORIES_FILTER = i94;
        int i96 = i95 + 1;
        f340id = i96;
        CHANNELS_CATEGORIES_FILTER = i95;
        int i97 = i96 + 1;
        f340id = i97;
        ADMIN_CATEGORIES_FILTER = i96;
        int i98 = i97 + 1;
        f340id = i98;
        OWNER_CATEGORIES_FILTER = i97;
        f340id = i98 + 1;
        BOTS_CATEGORIES_FILTER = i98;
    }
}
