package com.iMe.common;
/* loaded from: classes3.dex */
public class IdFabric$CustomType {
    public static final int CHAT_ATTACH_ALERT_WALLET;
    public static final int CHAT_ATTACH_ALERT_WALLET_BINANCE;
    public static final int CHAT_ATTACH_ALERT_WALLET_TEMPLATES;
    public static final int CHAT_FORWARDING_EDITOR;
    public static final int CONTACTS_PRIVACY_SETTINGS;
    public static final int CONTENT_TYPE_KIKLIKO;
    public static final int CONTENT_TYPE_NFT;
    public static final int DRAWER_USER_CELL_ACTION_BAR_ACCOUNT_SWITCH;
    public static final int LANGUAGE_SELECT_CATALOG;
    public static final int LOGIN_SEARCH_BY_TEL;
    public static final int MEDIA_MUSIC = -1073741824;
    public static final int MEDIA_TAB_PLAYLIST;
    public static final int QR_BOTTOM_SHEET_LOGIN_TOKEN;
    public static final int QR_BOTTOM_SHEET_WALLET_BACKUP;
    public static final int QR_BOTTOM_SHEET_WALLET_RECEIVE;
    public static final int QR_CODE_SCANNER_CHAT_LINK;
    public static final int SHARED_AUDIO_CELL_MUSIC;
    public static final int SHARED_MEDIA_LAYOUT_MUSIC;
    public static final int TRANSFORMABLE_LOGIN_BUTTON_SEARCH;
    public static final int UNDO_ACTION_CHAT_UNARCHIVED_FEW;
    public static final int UNDO_IMAGE_COPIED;
    public static final int UNDO_MOVE_TO_FOLDER;

    /* renamed from: id */
    private static int f338id = -1073741824;

    static {
        int i = (-1073741824) + 1;
        f338id = i;
        int i2 = i + 1;
        f338id = i2;
        MEDIA_TAB_PLAYLIST = i;
        int i3 = i2 + 1;
        f338id = i3;
        SHARED_MEDIA_LAYOUT_MUSIC = i2;
        int i4 = i3 + 1;
        f338id = i4;
        LOGIN_SEARCH_BY_TEL = i3;
        int i5 = i4 + 1;
        f338id = i5;
        TRANSFORMABLE_LOGIN_BUTTON_SEARCH = i4;
        int i6 = i5 + 1;
        f338id = i6;
        CONTENT_TYPE_KIKLIKO = i5;
        int i7 = i6 + 1;
        f338id = i7;
        CONTENT_TYPE_NFT = i6;
        int i8 = i7 + 1;
        f338id = i8;
        LANGUAGE_SELECT_CATALOG = i7;
        int i9 = i8 + 1;
        f338id = i9;
        CONTACTS_PRIVACY_SETTINGS = i8;
        int i10 = i9 + 1;
        f338id = i10;
        CHAT_FORWARDING_EDITOR = i9;
        int i11 = i10 + 1;
        f338id = i11;
        UNDO_MOVE_TO_FOLDER = i10;
        int i12 = i11 + 1;
        f338id = i12;
        UNDO_IMAGE_COPIED = i11;
        int i13 = i12 + 1;
        f338id = i13;
        UNDO_ACTION_CHAT_UNARCHIVED_FEW = i12;
        int i14 = i13 + 1;
        f338id = i14;
        QR_CODE_SCANNER_CHAT_LINK = i13;
        int i15 = i14 + 1;
        f338id = i15;
        CHAT_ATTACH_ALERT_WALLET = i14;
        int i16 = i15 + 1;
        f338id = i16;
        CHAT_ATTACH_ALERT_WALLET_BINANCE = i15;
        int i17 = i16 + 1;
        f338id = i17;
        CHAT_ATTACH_ALERT_WALLET_TEMPLATES = i16;
        int i18 = i17 + 1;
        f338id = i18;
        DRAWER_USER_CELL_ACTION_BAR_ACCOUNT_SWITCH = i17;
        int i19 = i18 + 1;
        f338id = i19;
        SHARED_AUDIO_CELL_MUSIC = i18;
        int i20 = i19 + 1;
        f338id = i20;
        QR_BOTTOM_SHEET_WALLET_RECEIVE = i19;
        int i21 = i20 + 1;
        f338id = i21;
        QR_BOTTOM_SHEET_WALLET_BACKUP = i20;
        f338id = i21 + 1;
        QR_BOTTOM_SHEET_LOGIN_TOKEN = i21;
    }
}
